#ddev-generated
# Simple template to demonstrate mockoon
services:
  mockoon:
    container_name: ddev-${DDEV_SITENAME}-mockoon
    image: mockoon/cli:latest
    command: ["-d", "/apiMocks"]
    networks: [default, ddev_default]
    restart: "no"
    expose:
      - "3000"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
    - "../apiMocks:/apiMocks"
